# Generated by Django 4.0.3 on 2022-03-19 13:54

from django.db import migrations

def create_initial_products(apps, schema_editor):
    Product = apps.get_model('products', 'Product')

    Product(name='Coca-cola',  price=1,   quantity=10).save()
    Product(name='Appletiser', price=2,   quantity=10).save()
    Product(name='Fanta',      price=1,   quantity=10).save()
    Product(name='Mirinda',    price=1,   quantity=10).save()
    Product(name='Gatorade',   price=1.5, quantity=10).save()
    Product(name='Sprite',     price=1.5, quantity=10).save()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_products),
    ]
